---

- hosts: webservers
  become: true
<<<<<<< HEAD

  vars:
    ansible_become_pass: "{{ jenkins_sudo_pass }}"
=======
  
  vars:
    ansible_become_pass: jenkins
>>>>>>> 4f55bbef2f78321fa8062a2fa0cd6f1d2fc4c74f
 
  tasks:
    - name: install tomcat
      ansible.builtin.yum:
        name:
          - tomcat 
          - tomcat-webapps
          - tomcat-admin-webapps 
          - tomcat-docs-webapp
        state: present
        
    
    - name: start and enable the tomcat service
      ansible.builtin.service:
        name: tomcat
        state: started
        enabled: yes



...
